// scripts/generate-version.js
// Purpose: Writes the release version provided by semantic-release to src/version.ts
// Called by: @semantic-release/exec during the 'prepare' step

// Using CommonJS require as this script might run directly with node
// before full ESM context is established in all environments.
const fs = require('fs');
const path = require('path');

// Get version from the command line argument passed by semantic-release exec
const version = process.argv[2];

if (!version) {
  console.error('Error: No version argument provided to generate-version.js!');
  process.exit(1);
}

// Basic check for semantic version format (adjust regex if needed)
if (!/^\d+\.\d+\.\d+(-[\w.-]+)?(\+[\w.-]+)?$/.test(version)) {
  console.error(`Error: Invalid version format received: "${version}"`);
  process.exit(1);
}

const content = `// Auto-generated by scripts/generate-version.js during semantic-release prepare step
// Do not edit this file manually.

export const VERSION = '${version}';
`;

// Construct the absolute path to src/version.ts
const filePath = path.join(__dirname, '..', 'src', 'version.ts');
const fileDir = path.dirname(filePath);

try {
  // Ensure the src directory exists (though it should)
  if (!fs.existsSync(fileDir)) {
    fs.mkdirSync(fileDir, { recursive: true });
  }
  // Write the version file
  fs.writeFileSync(filePath, content, { encoding: 'utf-8' });
  console.log(`Successfully wrote version ${version} to ${filePath}`);
} catch (error) {
  console.error(`Error writing version file to ${filePath}:`, error);
  process.exit(1);
}
