#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format all staged files
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
